name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://${{ vars.MONGO_USERNAME }}:${{ secrets.MONGO_PASSWORD }}@cluster0.sy4jwmi.mongodb.net/superData
  MONGO_USERNAME:    ${{ vars.MONGO_USERNAME }} #superuser'
  MONGO_PASSWORD:   ${{ secrets.MONGO_PASSWORD }} #'Password123'
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v7.0.1

        - name: Setup NodeJS Version
          uses: actions/setup-node@v7.0.0
          with:
            node-version: '20'
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v7.0.1
          with:
            name: Mocha-Test-Result
            path: test-results.xml